# Generated by Django 4.0.4 on 2022-05-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('price', models.SmallIntegerField(blank=True)),
            ],
        ),
    ]
