# Generated by Django 4.0.4 on 2022-05-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_tracker_app', '0004_delete_coderesponse_productcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
