# Generated by Django 4.0.4 on 2022-05-12 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_tracker_app', '0007_alter_productcard_vendor_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorCode',
        ),
        migrations.AddField(
            model_name='productcard',
            name='date_from',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$')]),
        ),
        migrations.AddField(
            model_name='productcard',
            name='date_to',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$')]),
        ),
    ]
