# Generated by Django 4.0.4 on 2022-05-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_tracker_app', '0008_delete_vendorcode_productcard_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
